Implement io.Writer interface
chewxy/skiprope pull request #11
Opened 2017-10-31 13:28 UTC by codegoalie

[Closes #4]

2017-10-31 19:36 UTC, chewxy requested changes
Thank you so much for this pull request. I'm unsure about the decision to erase, rather than just append. I was rather hoping you could help me understand this one

2017-10-31 19:36 UTC, chewxy commented on rope.go
> +	_ = r.EraseAt(0, r.Size())
Is there a reason for erasing it? Typical `io.Writer`s don't erase, just append

2017-11-02 13:20 UTC, codegoalie commented
@chewxy You are right. Multiple calls to the same `Writer` would just append. I've fixed that in 2100014.

2017-11-02 19:41 UTC, chewxy approved these changes
thank you very much

2017-11-02 19:42 UTC, merged